### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by aAMYzsy** [garrickbrazil/M3D-RPN#5]
I got an error with the following message, I don not known how to solve it, could you help me?

Traceback (most recent call last):
  File "scripts/train_rpn_3d.py", line 197, in <module>
    main(sys.argv[1:])
  File "scripts/train_rpn_3d.py", line 123, in main
    cls, prob, bbox_2d, bbox_3d, feat_size = rpn_net(images)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

**Comment by liulj13** [comment]
I came into the same problem. The solution is to add os.environ["CUDA_VISIBLE_DEVICES"] = '0' in the train_rpn_3d.py. Using more than one GPU would cause this problem.

**Comment by aAMYzsy** [comment]
The problem has been solved, thank you!
